Разметка главной страницы
htmlacademy-adaptive/1052625-pink-24 pull request #2
Opened 2021-11-27 12:28 UTC by NickOrlovsky

2021-11-27 17:06 UTC, baronin requested changes
Хорошая работа

2021-11-27 17:06 UTC, baronin commented on source/index.html
> +          <li class="feedback__item feedback__item--current slider__item">
feedback__item slider__item - какой класс для чего нужен ?

2021-11-27 17:06 UTC, baronin commented on source/index.html
> +          <li class="pricing__item slider__item">
Думаю лучше поправить

2021-11-27 17:06 UTC, baronin commented on source/index.html
> +          <button class="slider__toggle" type="button">1</button>
slider__toggle - думаю это все же кнопки, а не переключатель :)

2021-11-27 17:06 UTC, baronin commented on source/index.html
> +          <li class="contacts__item">
-

2021-11-27 17:06 UTC, baronin commented on source/index.html
> +            <a href="#">mail@htmlacademy.ru</a>
а тут не хватает к емейлу описания в  href :)

2021-11-28 18:43 UTC, NickOrlovsky commented on source/img/social icons/facebook.svg
> +<svg width="9" height="18" viewBox="0 0 9 18" fill="none" xmlns="http://www.w3.org/2000/svg">
пофиксил

2021-11-28 18:43 UTC, NickOrlovsky commented on source/index.html
> +          <li class="main-nav__item">
исправил

2021-11-28 18:44 UTC, NickOrlovsky commented on source/index.html
> +    <h1 class="visually-hidden"> Pink - Взгляните на жизнь
Заменил надпись и оставил это скрытым блоком

2021-11-28 18:45 UTC, NickOrlovsky commented on source/index.html
> +    <section class="app">
поменял на intro

2021-11-28 18:45 UTC, NickOrlovsky commented on source/index.html
> +        <div class="app__download">
переименовал добавив к названию wrapper

2021-11-28 18:45 UTC, NickOrlovsky commented on source/index.html
> +            <li class="app__logo-item">
пофиксил

2021-11-28 18:46 UTC, NickOrlovsky commented on source/index.html
> +          <li class="advantages__item">
пофиксил

2021-11-28 18:46 UTC, NickOrlovsky commented on source/index.html
> +          <li class="feedback__item feedback__item--current slider__item">
пофиксил, как мы обсудили

2021-11-28 18:46 UTC, NickOrlovsky commented on source/index.html
> +          <li class="pricing__item slider__item">
пофиксил

2021-11-28 18:47 UTC, NickOrlovsky commented on source/index.html
> +          <button class="slider__toggle" type="button">1</button>
переименовал на slider__button

2021-11-28 18:47 UTC, NickOrlovsky commented on source/index.html
> +          <li class="contacts__item">
пофиксил

2021-11-28 18:47 UTC, NickOrlovsky commented on source/index.html
> +            <a href="#">mail@htmlacademy.ru</a>
дабавил имейл в href

2021-11-29 20:36 UTC, baronin requested changes

2021-11-29 20:36 UTC, baronin commented on source/img/social icons/facebook.svg
> +<svg width="9" height="18" viewBox="0 0 9 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Папка social icons(с пробелом) осталось, удали ее пожалуйста

2021-11-29 20:36 UTC, baronin commented on source/index.html
> +          <li class="advantages__item">
А этот класс упустил ?)

2021-11-29 20:36 UTC, baronin commented on source/index.html
> +            <li class="intro__logo-list-item">
Я думаю тут так же должны быть ссылки, что бы мы могли перейти на страницу и скачать приложение

2021-11-29 20:36 UTC, baronin commented on source/index.html
> +            <div class="pricing__headline">
А где надпись "ХИТ" ? :)

2021-11-29 20:36 UTC, baronin commented on source/index.html
> +      <p class="footer__logo">
Обычно логотипы это тоже ссылки

2021-11-29 20:36 UTC, baronin commented on source/index.html
> +        <svg width="27" height="34" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
Где-то в критериях написано, что логотип академии ведет на сайт академии

2021-11-29 21:22 UTC, NickOrlovsky commented on source/index.html
> +          <li class="advantages__item">
поправил

2021-11-29 21:22 UTC, NickOrlovsky commented on source/index.html
> +            <li class="intro__logo-list-item">
добавил ссылки

2021-11-29 21:25 UTC, NickOrlovsky commented on source/index.html
> +            <div class="pricing__headline">
добавил

2021-11-29 21:27 UTC, NickOrlovsky commented on source/index.html
> +      <p class="footer__logo">
добавил ссылку

2021-11-29 21:30 UTC, NickOrlovsky commented on source/index.html
> +        <svg width="27" height="34" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
добавил cсылку на академию

2021-11-30 18:22 UTC, baronin requested changes

2021-11-30 18:22 UTC, baronin commented on source/index.html
> +          <li class="main-nav__item">
Не корректный класс :)

2021-11-30 18:22 UTC, baronin commented on source/index.html
> +          <li class="feedback__list-item feedback__list-item--current slider__list-item">
Подскажи, а где родитель у slider__list-item ?

2021-11-30 18:22 UTC, baronin commented on source/index.html
> +            <a href="mail@htmlacademy.ru">mail@htmlacademy.ru</a>
тут пример как правильно заполнить ссылку с емеил
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

2021-11-30 20:56 UTC, merged