Сетки для глав. страницы
htmlacademy-adaptive/1052625-pink-24 pull request #5
Opened 2021-12-11 22:30 UTC by NickOrlovsky

С блоком advantages судя по всему накосячил, но лучшего способа сделать картинки экранов не придумал.

2021-12-12 22:07 UTC, baronin requested changes

2021-12-12 22:07 UTC, baronin commented on source/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1">
На 320 страница выглядит не по макету
![image](https://user-images.githubusercontent.com/20131942/145731264-99456df4-2b19-4d6c-9c2f-3e0673f675e1.png)

2021-12-12 22:07 UTC, baronin commented on source/index.html
>        <div class="pricing__wrapper">
Этот блок не по макету на моб, версии
![image](https://user-images.githubusercontent.com/20131942/145731379-048377eb-1008-4f7f-9dd5-bd7dbe20fef5.png)

2021-12-14 09:37 UTC, NickOrlovsky commented on source/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1">
После фикса pricing, горизонтальная прокрутка пропала

2021-12-14 09:37 UTC, NickOrlovsky commented on source/index.html
>        <div class="pricing__wrapper">
пофиксил

2021-12-14 16:08 UTC, baronin requested changes

2021-12-14 16:08 UTC, baronin commented on source/less/components/intro.less
> +    max-width: 300px;
Мы не должны ограничивать ширину, мы стараемся делать максимальный респонсив под все возможные девайсы

2021-12-15 21:43 UTC, NickOrlovsky commented on source/index.html
>    <main class="page__main">
Добавил контейнеры

2021-12-15 21:44 UTC, NickOrlovsky commented on source/index.html
> +        <div class="advantages__list-wrapper">
поправил

2021-12-15 21:44 UTC, NickOrlovsky commented on source/less/components/intro.less
> +    max-width: 300px;
убрал

2021-12-16 19:53 UTC, merged

2021-12-16 19:57 UTC, baronin approved these changes